'''로그인 페이지, 시그니처 색깔'''
MAIN_COLOR = "#004080"
ACTIVE_COLOR = "#22C7E8"
PAGE_BG = "#FFFFFF"

'''텍스트에 사용하는 색깔'''
BOX_BG = "#FFFFFF"      
TEXT_PRIMARY = "#2B2F36"
TEXT_SECONDARY = "#6B7280"
TEXT_MUTED = "#9CA3AF"

'''홈화면 반원차트 '''
CARD_BG = "#FFFFFF"
TRACK_COLOR = "#D9DDE3"
VALUE_COLOR = "#0B4F8A"
TEXT_PRIMARY = "#2B2F36"
TEXT_SECONDARY = "#6B7280"
TEXT_TERTIARY = "#BEBEBE"

'''side/top_bar에서 사용하는 색깔'''
DIVIDER_COLOR = "#2A679B"
SUBTEXT_COLOR = "#9CC3DF"
EXPANDED_PANEL_BG = "#E9EAF2"
EXPANDED_TEXT_COLOR = "#111111"
EXPANDED_ACTIVE_BG = "#004C8C"

'''재고 비중 원 차트용 색깔'''
CARD_BG = "#FFFFFF"
TEXT_PRIMARY = "#2B2F36"
TEXT_SECONDARY = "#6B7280"
TEXT_MUTED = "#9CA3AF"

PIE_BLUE = "#0B4F8A"
PIE_SKY = "#4DA3D9"
PIE_LIGHT = "#BFD9EA"

CHART_LINE_COLOR = "#0B4F8A"
CHART_POINT_COLOR = "#0EA5E9"
CHART_GRID_COLOR = "#E5E7EB"
BAR_COLOR = "#AFAFAF"

CHART_HEIGHT = 240
CHART_MAX_Y = 80  # ☑️ 수정: 데이터 값(20~80)에 맞게 Y축 최대값을 80으로 변경

'''registration_popup(팝업창에서 사용하는 색깔)'''
INCORRECT_POPUPCOLOR = "#b51919"

'''status box: 상태박스(production_status_box)'''
BORDER_LIGHT = "#D9DDE3"
BAR_ACTIVE = "#0B4F8A"

'''merchadies(상품재고) colors'''
FIELD_BORDER = "#D1D5DB"
FIELD_TEXT = "#222222"
BUTTON_BG = "#F3F4F6"
BUTTON_TEXT = "#374151"
TABLE_HEADER_BG = "#F9FAFB"
TEXT_ROW = "#374151"
TABLE_BORDER="#CBCBCB"

