class Product:
    guide_product_list = {
        # product_id:product_detail
        4: {"image_src":"test_product_4.jpg",
            "brand":"더리얼 독",
            "product_name":"1",
            "sales_price":"999999"},
        14:{"image_src":"test_product_14.jpg",
            "brand":"더리얼 독",
            "product_name":"2",
            "sales_price":"999899"},
        44:{"image_src":"test_product_4.jpg",
            "brand":"더리얼 독",
            "product_name":"3",
            "sales_price":"999799"},
        112: {"image_src":"test_product_4.jpg",
            "brand":"밥이보약",
            "product_name":"4",
            "sales_price":"999999"},
        114:{"image_src":"test_product_14.jpg",
            "brand":"더리얼 독",
            "product_name":"5",
            "sales_price":"999899"},
        144:{"image_src":"test_product_44.jpg",
            "brand":"밥이보약",
            "product_name":"666666666666666666645444444444447777777777788679999900",
            "sales_price":"999799"},
        224: {"image_src":"test_product_4.jpg",
            "brand":"더리얼 독",
            "product_name":"7",
            "sales_price":"999999"},
        225:{"image_src":"test_product_14.jpg",
            "brand":"더리얼 독",
            "product_name":"8",
            "sales_price":"999899"},
        244:{"image_src":"test_product_44.jpg",
            "brand":"더리얼 독",
            "product_name":"9",
            "sales_price":"999799"},
        310: {"image_src":"test_product_4.jpg",
            "brand":"밥이보약",
            "product_name":"10",
            "sales_price":"999999"},
        314:{"image_src":"test_product_14.jpg",
            "brand":"더리얼 독",
            "product_name":"11",
            "sales_price":"999899"},
        344:{"image_src":"test_product_44.jpg",
            "brand":"더리얼 독",
            "product_name":"12",
            "sales_price":"999799"},
    }

    guide_product_list_t = {
        # product_id:product_detail
        114:{"image_src":"test_product_14.jpg",
            "brand":"밥이보약",
            "product_name":"5",
            "sales_price":"999899"},
        144:{"image_src":"test_product_44.jpg",
            "brand":"더리얼 독",
            "product_name":"6",
            "sales_price":"999799"},
        224: {"image_src":"test_product_4.jpg",
            "brand":"더리얼 독",
            "product_name":"7",
            "sales_price":"999999"},
        225:{"image_src":"test_product_14.jpg",
            "brand":"밥이보약",
            "product_name":"8",
            "sales_price":"999899"},
        244:{"image_src":"test_product_44.jpg",
            "brand":"더리얼 독",
            "product_name":"9",
            "sales_price":"999799"},
        310: {"image_src":"test_product_4.jpg",
            "brand":"더리얼 독",
            "product_name":"10",
            "sales_price":"999999"},
    }
