PRODUCT_MASTER_FIELDS = [
    {
        "label": "제품코드",
        "key": "product_code",
        "type": "text",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "상품명",
        "key": "product_name",
        "type": "text",
        "required": True,
        "max_length": 50,
    },
    {
        "label": "상품종류",
        "key": "product_type",
        "type": "text",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "브랜드",
        "key": "brand",
        "type": "text",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "제조사",
        "key": "manufacturer",
        "type": "text",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "소비자판매가",
        "key": "consumer_price",
        "type": "int",
        "required": True,
        "max_length": 10,
    },
    {
        "label": "규격(중량)",
        "key": "spec_weight",
        "type": "float",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "바코드",
        "key": "barcode",
        "type": "int",
        "required": False,
        "max_length": 20,
    },
    {
        "label": "재고단위",
        "key": "stock_unit",
        "type": "text",
        "required": False,
        "max_length": 20,
    },
    {
        "label": "판매 상태",
        "key": "sale_status",
        "type": "text",
        "required": True,
        "max_length": 20,
    },
]

PRODUCT_DETAIL_FIELDS = [
    {
        "label": "제품코드",
        "key": "product_code",
        "type": "text",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "상품명",
        "key": "product_name",
        "type": "text",
        "required": True,
        "max_length": 50,
    },
    {
        "label": "상품 이미지",
        "key": "product_image",
        "type": "url",
        "required": False,
        "max_length": 300,
    },
    {
        "label": "상품 상세페이지",
        "key": "product_detail_page",
        "type": "url",
        "required": False,
        "max_length": 300,
    },
    {
        "label": "상품종류",
        "key": "product_type",
        "type": "text",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "브랜드",
        "key": "brand",
        "type": "text",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "제조사",
        "key": "manufacturer",
        "type": "text",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "소비자판매가",
        "key": "consumer_price",
        "type": "int",
        "required": True,
        "max_length": 10,
    },
    {
        "label": "원가",
        "key": "cost",
        "type": "int",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "중량",
        "key": "weight",
        "type": "float",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "기능",
        "key": "function",
        "type": "text",
        "required": False,
        "max_length": 100,
    },
    {
        "label": "설명",
        "key": "description",
        "type": "text",
        "required": False,
        "max_length": 500,
    },
    {
        "label": "조단백",
        "key": "crude_protein",
        "type": "float",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "조지방",
        "key": "crude_fat",
        "type": "float",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "조회분",
        "key": "crude_ash",
        "type": "float",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "조섬유",
        "key": "crude_fiber",
        "type": "float",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "수분",
        "key": "moisture",
        "type": "float",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "칼슘",
        "key": "calcium",
        "type": "float",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "인",
        "key": "phosphorus",
        "type": "float",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "열량",
        "key": "calorie",
        "type": "float",
        "required": False,
        "max_length": 10,
    },
]

CUSTOMER_FIELDS = [
    {
        "label": "거래처명",
        "key": "customer_name",
        "type": "text",
        "required": True,
        "max_length": 50,
    },
    {
        "label": "대표자명",
        "key": "ceo_name",
        "type": "text",
        "required": False,
        "max_length": 30,
    },
    {
        "label": "사업자번호",
        "key": "business_number",
        "type": "bizno",
        "required": False,
        "max_length": 12,
    },
    {
        "label": "우편번호",
        "key": "zip_code",
        "type": "postal",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "주소",
        "key": "address",
        "type": "text",
        "required": False,
        "max_length": 100,
    },
    {
        "label": "상세주소",
        "key": "address_detail",
        "type": "text",
        "required": False,
        "max_length": 100,
    },
    {
        "label": "전화번호",
        "key": "phone",
        "type": "phone",
        "required": False,
        "max_length": 20,
    },
    {
        "label": "팩스번호",
        "key": "fax",
        "type": "phone",
        "required": False,
        "max_length": 20,
    },
    {
        "label": "이메일주소",
        "key": "email",
        "type": "email",
        "required": False,
        "max_length": 100,
    },
    {
        "label": "담당자",
        "key": "manager_name",
        "type": "text",
        "required": False,
        "max_length": 30,
    },
    {
        "label": "비고",
        "key": "note",
        "type": "text",
        "required": False,
        "max_length": 300,
    },
]

EMPLOYEE_FIELDS = [
    {
        "label": "이름",
        "key": "employee_name",
        "type": "name",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "사번",
        "key": "employee_no",
        "type": "text",
        "required": True,
        "max_length": 20,
    },
    {
        "label": "부서",
        "key": "department",
        "type": "text",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "직급",
        "key": "position",
        "type": "text",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "생년월일",
        "key": "birth_date",
        "type": "date",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "전화번호",
        "key": "phone",
        "type": "phone",
        "required": True,
        "max_length": 20,
    },
    {
        "label": "이메일",
        "key": "email",
        "type": "email",
        "required": True,
        "max_length": 100,
    },
    {
        "label": "주소",
        "key": "address",
        "type": "text",
        "required": False,
        "max_length": 100,
    },
    {
        "label": "입사일",
        "key": "hire_date",
        "type": "date",
        "required": True,
        "max_length": 10,
    },
    {
        "label": "비고",
        "key": "note",
        "type": "text",
        "required": False,
        "max_length": 300,
    },
]

# =========================================================
# ☑️ 추가: 고객 등록 필드
# =========================================================
CLIENT_FIELDS = [
    {
        "label": "고객명",
        "key": "client_name",
        "type": "name",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "고객 ID",
        "key": "client_id",
        "type": "text",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "전화번호",
        "key": "phone",
        "type": "phone",
        "required": True,
        "max_length": 20,
    },
    {
        "label": "우편번호",
        "key": "zip_code",
        "type": "postal",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "주소",
        "key": "address",
        "type": "text",
        "required": False,
        "max_length": 100,
    },
    {
        "label": "상세주소",
        "key": "address_detail",
        "type": "text",
        "required": False,
        "max_length": 100,
    },
    {
        "label": "생년월일",
        "key": "birth_date",
        "type": "date",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "성별",
        "key": "gender",
        "type": "text",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "고객등급",
        "key": "client_grade",
        "type": "text",
        "required": False,
        "max_length": 20,
    },
    {
        "label": "구독여부",
        "key": "is_subscribed",
        "type": "text",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "비고",
        "key": "note",
        "type": "text",
        "required": False,
        "max_length": 300,
    },
]