PRODUCT_MASTER_FIELDS = [
    {
        "label": "제품코드",
        "key": "product_code",
        "type": "text",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "상품명",
        "key": "product_name",
        "type": "text",
        "required": True,
        "max_length": 50,
    },
    {
        "label": "상품종류",
        "key": "product_type",
        "type": "text",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "브랜드",
        "key": "brand",
        "type": "text",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "제조사",
        "key": "manufacturer",
        "type": "text",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "소비자판매가",
        "key": "consumer_price",
        "type": "int",
        "required": True,
        "max_length": 10,
    },
    {
        "label": "규격(중량)",
        "key": "spec_weight",
        "type": "float",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "바코드",
        "key": "barcode",
        "type": "int",
        "required": False,
        "max_length": 20,
    },
    {
        "label": "재고단위",
        "key": "stock_unit",
        "type": "text",
        "required": False,
        "max_length": 20,
    },
    {
        "label": "판매 상태",
        "key": "sale_status",
        "type": "text",
        "required": True,
        "max_length": 20,
    },
]


PRODUCT_DETAIL_FIELDS = [
    {
        "label": "타입",
        "key": "type",
        "type": "text",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "브랜드",
        "key": "brand",
        "type": "text",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "상품명",
        "key": "product_name",
        "type": "text",
        "required": True,
        "max_length": 100,
    },
    {
        "label": "기능",
        "key": "function",
        "type": "text",
        "required": False,
        "max_length": 200,
    },
    {
        "label": "설명",
        "key": "description",
        "type": "text",
        "required": False,
        "max_length": 500,
    },
    {
        "label": "조단백",
        "key": "crude_protein",
        "type": "float",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "조지방",
        "key": "crude_fat",
        "type": "float",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "칼로리",
        "key": "calories",
        "type": "float",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "썸네일 URL",
        "key": "thumbnail",
        "type": "url",
        "required": False,
        "max_length": 300,
    },
    {
        "label": "알갱이 크기",
        "key": "kibble_size",
        "type": "text",
        "required": False,
        "max_length": 50,
    },
    {
        "label": "급여 단계",
        "key": "life",
        "type": "text",
        "required": False,
        "max_length": 30,
    },
    {
        "label": "단백질 유형",
        "key": "protein_type",
        "type": "text",
        "required": False,
        "max_length": 30,
    },
    {
        "label": "주원료",
        "key": "main_protein",
        "type": "text",
        "required": False,
        "max_length": 100,
    },
    {
        "label": "인증",
        "key": "certified",
        "type": "text",
        "required": False,
        "max_length": 100,
    },
    {
        "label": "보존제",
        "key": "preservative",
        "type": "text",
        "required": False,
        "max_length": 100,
    },
    {
        "label": "사료 형태",
        "key": "feedshape",
        "type": "text",
        "required": False,
        "max_length": 50,
    },
]

CUSTOMER_FIELDS = [
    {
        "label": "고객ID",
        "key": "customer_id",
        "type": "int",
        "required": True,
        "max_length": 10,
    },
    {
        "label": "구독여부",
        "key": "is_subscribed",
        "type": "text",
        "required": True,
        "max_length": 10,
    },
    {
        "label": "구독횟수",
        "key": "subs_count",
        "type": "int",
        "required": True,
        "max_length": 10,
    },
    {
        "label": "권한",
        "key": "permission",
        "type": "int",
        "required": True,
        "max_length": 10,
    },
    {
        "label": "상태",
        "key": "active",
        "type": "text",
        "required": True,
        "max_length": 10,
    },
]


EMPLOYEE_FIELDS = [
    {
        "label": "사원ID",
        "key": "employee_id",
        "type": "int",
        "required": True,
        "max_length": 10,
    },
    {
        "label": "계정ID",
        "key": "account_id",
        "type": "text",
        "required": True,
        "max_length": 50,
    },
    {
        "label": "이름",
        "key": "username",
        "type": "name",
        "required": True,
        "max_length": 30,
    },
    {
        "label": "입사일",
        "key": "hire_date",
        "type": "date",
        "required": True,
        "max_length": 10,
    },
    {
        "label": "퇴사일",
        "key": "quit_date",
        "type": "date",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "직급ID",
        "key": "emp_position_id",
        "type": "int",
        "required": True,
        "max_length": 10,
    },
    {
        "label": "관리자ID",
        "key": "manager_id",
        "type": "int",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "이메일",
        "key": "email",
        "type": "email",
        "required": True,
        "max_length": 100,
    },
    {
        "label": "전화번호",
        "key": "phone",
        "type": "phone",
        "required": True,
        "max_length": 20,
    },
    {
        "label": "주소",
        "key": "address",
        "type": "text",
        "required": False,
        "max_length": 100,
    },
    {
        "label": "우편번호",
        "key": "postal_code",
        "type": "postal",
        "required": False,
        "max_length": 10,
    },
    {
        "label": "재직여부",
        "key": "active",
        "type": "text",
        "required": True,
        "max_length": 10,
    },
]